core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')) 
]

main/urls.py
from django.urls import path
from main.views import *

 

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('disclaimer', TemplateView.as_view(template_name="disclaimer.html"), name="disclaimer"),
    
    # KCET CUTOFF ROUTES
    path('kcet-cutoff', CutoffAnalyserView().main, name="kcet-cutoff"),
    path('kcet-cutoff/upload', CutoffAnalyserView().upload, name="cutoff-upload"),
    path("kcet-cutoff/ajax/get-courses", CutoffAnalyserView().get_courses),
    path("kcet-cutoff/ajax/get-data", CutoffAnalyserView().get_data),


    # College Seat Analyser
    path("seat-analyser", SeatAnalyserView().main, name = "seat-analyser"),
    path('seat-analyser/upload', SeatAnalyserView().upload, ),
    path('seat-analyser/ajax/get-courses', SeatAnalyserView().get_courses),
    path('seat-analyser/ajax/get-districts', SeatAnalyserView().get_districts),
    path('seat-analyser/ajax/get-colleges', SeatAnalyserView().get_colleges),
    path('seat-analyser/ajax/get-seat-matrix', SeatAnalyserView().get_seat_matrix),
]

main/models.py
from django.db import models


class Cutoff(models.Model):
    round = models.CharField(max_length=10000, null=True, blank=True)
    category = models.CharField(max_length=1000, null = True, blank = True)
    code = models.CharField(max_length=10000, null=True, blank=True)
    college = models.CharField(max_length=10000, null=True, blank=True)
    course = models.CharField(max_length=10000, null=True, blank=True)
    _1G = models.IntegerField(blank=True, null=True)
    _1K = models.IntegerField(blank=True, null=True)
    _1R = models.IntegerField(blank=True, null=True)
    _2AG = models.IntegerField(blank=True, null=True)
    _2AK = models.IntegerField(blank=True, null=True)
    _2AR = models.IntegerField(blank=True, null=True)
    _2BG = models.IntegerField(blank=True, null=True)
    _2BK = models.IntegerField(blank=True, null=True)
    _2BR = models.IntegerField(blank=True, null=True)
    _3AG = models.IntegerField(blank=True, null=True)
    _3AK = models.IntegerField(blank=True, null=True)
    _3AR = models.IntegerField(blank=True, null=True)
    _3BG = models.IntegerField(blank=True, null=True)
    _3BK = models.IntegerField(blank=True, null=True)
    _3BR = models.IntegerField(blank=True, null=True)
    _GM = models.IntegerField(blank=True, null=True)
    _GMK = models.IntegerField(blank=True, null=True)
    _GMP = models.IntegerField(blank=True, null=True)
    _GMR = models.IntegerField(blank=True, null=True)
    _SCG = models.IntegerField(blank=True, null=True)
    _SCK = models.IntegerField(blank=True, null=True)
    _SCR = models.IntegerField(blank=True, null=True)
    _STG = models.IntegerField(blank=True, null=True)
    _STK = models.IntegerField(blank=True, null=True)
    _STR = models.IntegerField(blank=True, null=True)
    H_1G = models.IntegerField(blank=True, null=True)
    H_1K = models.IntegerField(blank=True, null=True)
    H_1R = models.IntegerField(blank=True, null=True)
    H_2AG = models.IntegerField(blank=True, null=True)
    H_2AK = models.IntegerField(blank=True, null=True)
    H_2AR = models.IntegerField(blank=True, null=True)
    H_2BG = models.IntegerField(blank=True, null=True)
    H_2BK = models.IntegerField(blank=True, null=True)
    H_2BR = models.IntegerField(blank=True, null=True)
    H_3AG = models.IntegerField(blank=True, null=True)
    H_3AK = models.IntegerField(blank=True, null=True)
    H_3AR = models.IntegerField(blank=True, null=True)
    H_3BG = models.IntegerField(blank=True, null=True)
    H_3BK = models.IntegerField(blank=True, null=True)
    H_3BR = models.IntegerField(blank=True, null=True)
    H_GM = models.IntegerField(blank=True, null=True)
    H_GMK = models.IntegerField(blank=True, null=True)
    H_GMR = models.IntegerField(blank=True, null=True)
    H_SCG = models.IntegerField(blank=True, null=True)
    H_SCK = models.IntegerField(blank=True, null=True)
    H_SCR = models.IntegerField(blank=True, null=True)
    H_STG = models.IntegerField(blank=True, null=True)
    H_STK = models.IntegerField(blank=True, null=True)
    H_STR = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.college) 





class SeatMatrix(models.Model):
    course_type = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'Course Type')
    district = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'District')
    type = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'Type')
    code = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'Code')
    college_short_name = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'College Short Name')
    college_full_name = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'College Full Name')
    course_code = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'Course Code')
    _1g = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '1G')
    _1k = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '1K')
    _1r = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '1R')
    _2ag = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2AG')
    _2ak = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2AK')
    _2ar = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2AR')
    _2bg = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2BG')
    _2bk = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2BK')
    _2br = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2BR')
    _3ag = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3AG')
    _3ak = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3AK')
    _3ar = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3AR')
    _3bg = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3BG')
    _3bk = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3BK')
    _3br = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3BR')
    gm = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'GM')
    gmk = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'GMK')
    gmp = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'GMP')
    gmr = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'GMR')
    scg = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'SCG')
    sck = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'SCK')
    scr = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'SCR')
    stg = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'STG')
    stk = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'STK')
    str = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'STR')
    snq = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'SNQ')
    _1h = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '1H')
    _1kh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '1KH')
    _1rh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '1RH')
    _2ah = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2AH')
    _2akh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2AKH')
    _2arh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2ARH')
    _2bh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2BH')
    _2bkh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2BKH')
    _2brh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '2BRH')
    _3ah = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3AH')
    _3akh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3AKH')
    _3arh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3ARH')
    _3bh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3BH')
    _3bkh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3BKH')
    _3brh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = '3BRH')
    gmh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'GMH')
    gmkh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'GMKH')
    gmrh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'GMRH')
    sch = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'SCH')
    sckh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'SCKH')
    scrh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'SCRH')
    sth = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'STH')
    stkh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'STKH')
    strh = models.CharField(max_length = 1000, null=True, blank = True, verbose_name = 'STRH')



    def save(self, *args, **kwargs) -> None:
        if self.college_full_name is None:
            self.college_full_name = self.college_short_name
        return super(SeatMatrix, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.college_full_name+" - "+ self.course_code 

main/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import *
import openpyxl
from django.views.decorators.csrf import csrf_exempt
from main.models import Cutoff, SeatMatrix
# Create your views here.


class IndexView(TemplateView):
    template_name = "index.html"

class CutoffAnalyserView(object):
    def __init__(self) -> None:
        pass

    def main(self, request):
        context = {
            "course_categorys":Cutoff.objects.all().values_list("category", flat=True).distinct()
        }
        return render(request, "cutoff.html", context)

    @csrf_exempt
    def get_courses(self, request):
        category_name  = request.POST.get("course_category_name")
        courses = Cutoff.objects.filter(category = category_name).distinct().values_list("course", flat=True).order_by("-course")
        return JsonResponse({'courses':list(courses)})


    @csrf_exempt
    def get_data(self, request):
        course_name = request.POST.get("course")
        rank = request.POST.get("rank")
        reservation = request.POST.get("reservation")
        round = request.POST.get("round")
        cutoff_obj = Cutoff.objects.filter(**{
            "round": round, 
            "course":course_name,
            reservation+"__gte": rank
            })
        data = cutoff_obj.values_list("code", reservation, "college", "H"+reservation)
        return JsonResponse({"data":list(data.order_by(reservation).reverse())})


    def upload(self, request):
        if request.method == "POST":
            Cutoff.objects.all().delete()
            file = request.FILES.get("upload_file")
            wb = openpyxl.load_workbook(file).active
            fields = [i.name for i in Cutoff._meta.fields]
            fields.remove("id")
            for row in wb.iter_rows(min_row=2):
                values = [i.value for i in row]
                nary = dict(zip(fields,values))
                Cutoff.objects.get_or_create(**nary)
        return render(request, "cutoff-upload.html")



class SeatAnalyserView(object):

    def __init__(self) -> None:
        pass

    def main(self, request):    
        context = dict()
        context["category"] = SeatMatrix.objects.all().values("course_type").distinct().order_by("course_type") 
        return render(request, "seat-finder.html", context)


    @csrf_exempt
    def get_courses(self, request):
        category_name  = request.POST.get("category_name")
        courses = SeatMatrix.objects.filter(course_type = category_name).distinct().values_list("course_code", flat=True).order_by("-course_code")
        return JsonResponse({'courses':list(courses)})


    @csrf_exempt
    def get_districts(self, request):
        course_name = request.POST.get("course_name")
        category_name = request.POST.get("category_name")
        filter_dict = {}
        if course_name is not None:
            filter_dict["course_code"] = course_name
        if category_name is not None:
            filter_dict["course_type"] = category_name
        districts = SeatMatrix.objects.filter( **filter_dict).distinct().values_list("district", flat=True).order_by("district")
        return JsonResponse({'districts':list(districts)})


    @csrf_exempt
    def get_colleges(self, request):
        course_name = request.POST.get("course_name")
        category_name = request.POST.get("category_name")
        district_name = request.POST.get("district_name")
        filter_dict = {}
        if course_name is not None:
            filter_dict["course_code"] = course_name
        if category_name is not None:
            filter_dict["course_type"] = category_name
        if district_name is not None:
            filter_dict["district"] = district_name
        college_names = SeatMatrix.objects.filter(**filter_dict).distinct().values_list("college_full_name", flat=True).order_by("college_full_name")
        return JsonResponse({'colleges':list(college_names)})


    @csrf_exempt
    def get_seat_matrix(self, request):
        college_name = request.POST.get("college_name")
        course_name = request.POST.get("course_name")
        reservation_category = request.POST.get("reservation_category")
        reserved_seats_obj  = SeatMatrix.objects.filter(college_full_name = college_name, course_code = course_name)
        
        reserved_seats = reserved_seats_obj.values_list(reservation_category)[0][0]
        ga = list(reserved_seats_obj.values_list())[0][8:]
        total_seats = sum([int(i) for i in ga])

        seat_matrix_data = dict()
        seat_matrix_data["college_name"] = college_name
        seat_matrix_data["course_name"] = course_name
        seat_matrix_data["reservation_category"] = reservation_category.upper().replace("_", "")
        seat_matrix_data["total_seats"] = total_seats
        seat_matrix_data["reserved_seats"] = reserved_seats

        return JsonResponse({
            "seat_matrix_data":seat_matrix_data
        })



    def upload(self, request):
        if request.method == "POST":
            SeatMatrix.objects.all().delete()
            file = request.FILES.get("upload_file")
            wb = openpyxl.load_workbook(file)["Sheet1"]
            fields = [i.name for i in SeatMatrix._meta.fields]
            fields.remove("id")
            for row in wb.iter_rows(min_row=2):
                values = [i.value for i in row]
                nary = dict(zip(fields,values))
                SeatMatrix.objects.get_or_create(**nary)
        return render(request, "seat-upload.html")

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Career University</title>
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"></head>

<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
<style>
   * {
      font-family: 'Poppins', sans-serif;
    }
</style>
<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Career University</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'disclaimer' %}">Disclaimer</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}

  {% endblock content %}


  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css"> -->
</body>

</html>

main/templates/cutoff-upload.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="id_file" class="form-label">Upload Excel Sheet</label>
                  <input type="file" class="form-control" name="upload_file" id="id_file">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/cutoff.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1 class="m-3">KCET Cutoff Rank Analyser</h1>
    <div class="row my-3">
        <div class="col-md-6">
            <div class="card p-3 shadow">
                <div class="mb-3">
                    <label for="id_course_category" class="form-label">Select Your Course Category Under CET:</label>
                    <select class="form-control" id="id_course_category" onchange="get_courses(this.value);">
                        <option value="">--select--</option>
                        {% for category in course_categorys %}
                        <option value="{{ category }}">{{ category }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="id_course" class="form-label">Select your preferred course:</label>
                    <select class="form-control" id="id_course" onchange="get_cutoff_table()">
                    </select>
                </div>
                
                <div class="mb-3">
                  <label for="id_kcet_rank" class="form-label">Enter your KCET rank</label>
                  <input type="number" class="form-control" id="id_kcet_rank">  
                </div>
 
 
                <div class="mb-3">
                    <label for="id_category" class="form-label">Choose your reservation Category</label>
                    <select class="form-control" id="id_category" onchange="get_cutoff_table()">
                        <option>--select--</option>
                        <option value='_1G'>1G - 1 General</option>
                        <option value='_1K'>1K - 1 Kannada</option>
                        <option value='_1R'>1R - 1 Rural</option>
                        <option value='_2AG'>2AG - 2A General</option>
                        <option value='_2AK'>2AK - 2A Kannada</option>
                        <option value='_2AR'>2AR - 2A Rural</option>
                        <option value='_2BG'>2BG - 2B General</option>
                        <option value='_2BK'>2BK - 2B Kannada</option>
                        <option value='_2BR'>2BR - 2B Rural</option>
                        <option value='_3AG'>3AG - 3A General</option>
                        <option value='_3AK'>3AK - 3A Kannada</option>
                        <option value='_3AR'>3AR - 3A Rural</option>
                        <option value='_3BG'>3BG - 3B General </option>
                        <option value='_3BK'>3BK - 3B Kannada</option>
                        <option value='_3BR'>3BR - 3B Rural</option>
                        <option value='_GM'>GM - General Merit</option>
                        <option value='_GMK'>GMK - General Merit Kannada</option>
                        <option value='_GMP'>GMP - General Merit Private</option>
                        <option value='_GMR'>GMR - General Merit Rural</option>
                        <option value='_SCG'>SCG - Schedule Caste General</option>
                        <option value='_SCK'>SCK - Schedule Caste Kannada</option>
                        <option value='_SCR'>SCR - Schedule Caste Rural</option>
                        <option value='_STG'>STG - Schedule Tribe General</option>
                        <option value='_STK'>STK - Schedule Tribe Kannada</option>
                        <option value='_STR'>STR - Schedule Tribe Rural</option>
                    </select>

                </div>
                <div class="mb-3">
                    <label for="id_round" class="form-label">Select KCET Round:</label>
                    <select class="form-control" id="id_round" onchange="get_cutoff_table()">
                        <option value="Round 1">1st Round</option>
                        <option value="Round 2">2nd Round</option>
                        <option value="Round 2 Extended">2nd extended Round</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div id="id_data">

            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/cutoff.js' %}"></script>
{% endblock content %}

main/templates/disclaimer.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="m-2">Disclaimer</h1>
    <ul class="list-group">
        <li class="list-group-item">1. All data are as per last year admission information released by: 
            <ul>
                <li>KEA – Karnataka Examination Authority</li>
                <li>ComedK – Consortium of Medical, Engineering and Dental Colleges of Karnataka</li>
                <li>MCI – Medical Council of India</li>
            </ul>
        </li>
        <li class="list-group-item">2. Cutoff Rank changes every year. Last year cutoff rank should be taken for reference only.</li>
        <li class="list-group-item">3. Fees structure change every year as per Government notification.</li>
        <li class="list-group-item">4. Management fees structure provided by college management committee is displayed.</li>
    </ul>
</div>
{% endblock content %}

main/templates/seat-finder.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2 class="m-3">Find out seat availability based on your Reservation Category</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="card p-3 shadow">
                <div class="mb-3">
                    <label for="id_category" class="form-label">Select a Course Category:</label>
                    <select class="form-control" id="id_category">
                        <option>--select--</option>
                        {% for cat in category %}
                        <option value="{{cat.course_type}}">{{cat.course_type}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="id_course" class="form-label">Select a Course:</label>
                    <select class="form-control" id="id_course">
                    </select>
                </div>
                <div class="mb-3">
                    <label for="id_district" class="form-label">Select a Region / City / District:</label>
                    <select class="form-control" id="id_district">
                    </select>
                </div>
                <div class="mb-3">
                    <label for="id_college" class="form-label">Select a College:</label>
                    <select class="form-control" id="id_college">
                    </select>
                </div>
                <div class="mb-3">
                    <label for="id_reservation" class="form-label">Select Reservation Category:</label>
                    <select class="form-control" id="id_reservation">
                        <option>-- select --</option>
                        <option value='_1g'>1G</option>
                        <option value='_1k'>1K</option>
                        <option value='_1r'>1R</option>
                        <option value='_2ag'>2AG</option>
                        <option value='_2ak'>2AK</option>
                        <option value='_2ar'>2AR</option>
                        <option value='_2bg'>2BG</option>
                        <option value='_2bk'>2BK</option>
                        <option value='_2br'>2BR</option>
                        <option value='_3ag'>3AG</option>
                        <option value='_3ak'>3AK</option>
                        <option value='_3ar'>3AR</option>
                        <option value='_3bg'>3BG</option>
                        <option value='_3bk'>3BK</option>
                        <option value='_3br'>3BR</option>
                        <option value='gm'>GM</option>
                        <option value='gmk'>GMK</option>
                        <option value='gmp'>GMP</option>
                        <option value='gmr'>GMR</option>
                        <option value='scg'>SCG</option>
                        <option value='sck'>SCK</option>
                        <option value='scr'>SCR</option>
                        <option value='stg'>STG</option>
                        <option value='stk'>STK</option>
                        <option value='str'>STR</option>
                        <option value='snq'>SNQ</option>
                        <option value='_1h'>1H</option>
                        <option value='_1kh'>1KH</option>
                        <option value='_1rh'>1RH</option>
                        <option value='_2ah'>2AH</option>
                        <option value='_2akh'>2AKH</option>
                        <option value='_2arh'>2ARH</option>
                        <option value='_2bh'>2BH</option>
                        <option value='_2bkh'>2BKH</option>
                        <option value='_2brh'>2BRH</option>
                        <option value='_3ah'>3AH</option>
                        <option value='_3akh'>3AKH</option>
                        <option value='_3arh'>3ARH</option>
                        <option value='_3bh'>3BH</option>
                        <option value='_3bkh'>3BKH</option>
                        <option value='_3brh'>3BRH</option>
                        <option value='gmh'>GMH</option>
                        <option value='gmkh'>GMKH</option>
                        <option value='gmrh'>GMRH</option>
                        <option value='sch'>SCH</option>
                        <option value='sckh'>SCKH</option>
                        <option value='scrh'>SCRH</option>
                        <option value='sth'>STH</option>
                        <option value='stkh'>STKH</option>
                        <option value='strh'>STRH</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div id="id_seat_matrix_table"></div>

        </div>
    </div>
</div>

<script src="{% static 'js/seatfinder.js' %}"></script>

{% endblock content %}

main/templates/seat-upload.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="id_file" class="form-label">Upload Excel Sheet</label>
                  <input type="file" class="form-control" name="upload_file" id="id_file">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}